-- The charge engine's persistence: who pays the charge, and what the charge was made of.
--
-- TRX_TASK is THIS service's own table (V1), so widening it and hanging a child table off
-- it is regular schema work - the no-Flyway rule covers DATA and the legacy DIRECT tables,
-- not our own DDL (same reasoning as V5/V6/V7). Nothing here inserts a row: the tariffs
-- themselves live in the legacy CORP_CH_PC_DTL / COM_CH_PC_DTL tables and are read, never
-- seeded, by this service.
--
-- Column style follows V1: NVARCHAR2 text, 32-hex string surrogate keys, NUMBER(25,7)
-- amounts (BASE_FT's shape), NUMBER(18,7) rates (V7's shape), VERSION starting at 0,
-- CREATED_BY/CREATED_DT audit columns. No tablespace or storage clauses - they differ per
-- environment and would fail the migration wherever the named tablespace does not exist.
--
-- Do not edit this file once it has been applied anywhere. Flyway stores its checksum and
-- fails validation at boot if it changes. Corrections go in V13.

-- CHARGE_TO - who the charge is billed to. Exactly two values: N'REMITTER' (the payer's
-- account carries the fee) and N'BENEFICIARY' (the fee is taken out of what the
-- beneficiary receives). NULL on every task written before this migration, and NULL MEANS
-- REMITTER: that is the only behaviour the service had until now, so no backfill is needed
-- and none is done here.
--
-- Why a new word rather than a legacy code: legacy spells this same concept three
-- different ways and no two of them agree.
--   BASE_FT.CH_TO        '0' remitter / '1' beneficiary
--   the bulk tables      'D' debit (remitter) / 'C' credit (beneficiary) / 'S' shared
--   ACTV_LOG_FIN_DTL     'OUR' remitter / 'BEN' beneficiary / 'SHA' shared
-- Storing any one of those spellings here would force every other consumer to know which
-- dialect this table happens to speak. So this column holds the canonical WORD, and the
-- translation to the legacy alphabet happens at each legacy boundary, in the code that
-- writes that particular legacy row - one small mapping per boundary instead of a single
-- ambiguous code travelling through the whole system.
--
-- The arithmetic differs too, which is the part that gets missed: on N'BENEFICIARY' the
-- fee comes off the CREDIT side, so the debited total is the principal ALONE - not
-- principal + fee - and the beneficiary receives principal - fee. Any limit check, balance
-- check or debit posting that adds FEE_AMT unconditionally is wrong for those tasks.
ALTER TABLE TRX_TASK ADD (CHARGE_TO NVARCHAR2(20));

-- One row per charge COMPONENT, because a transfer does not carry "a fee": it carries
-- several, each with its own charge type, its own tariff and its own currency. Every
-- interbank service on this platform is billed as at least two components - LLG is
-- Transfer Fee (COM_MT_CH_TYP.CD 014) plus LLG Fee (009), RTGS is 014 plus RTGS Fee (012),
-- and so on - so a single FEE_AMT column can only ever hold the sum and can never answer
-- which component contributed what. That question is asked constantly by customer service
-- and by the billing reconciliation, hence this table.
--
-- BOTH SIDES OF THE CONVERSION ARE KEPT ON PURPOSE. AMT + CCY_CD are the tariff exactly as
-- the legacy tariff row states it (a charge may be denominated in USD while the transfer
-- is in IDR, or vice versa), and IDR_AMT + FX_RATE + FX_RATE_TYPE + FX_RATE_SIDE are the
-- IDR baseline figure with the rate that produced it. Keeping only the converted figure
-- would make "why is this number 27,500?" unanswerable six months later, when the rate of
-- that day is no longer recoverable from anywhere; keeping only the original would make
-- every reader re-derive the total. FX_RATE is NULL when CCY_CD is already IDR - there was
-- no conversion, and a 1 there would be indistinguishable from a real quote of 1.
--
-- THE RE-QUOTE COLUMNS NEVER OVERWRITE THE SUBMIT VALUES. When release re-quotes the rate
-- (the gap between submit and release can span days), the new figures land in
-- REQUOTED_IDR_AMT / REQUOTED_FX_RATE / REQUOTED_DT and AMT / IDR_AMT / FX_RATE stay
-- exactly as the maker and the approvers saw them. That is what makes "the approver
-- approved this number, the customer was charged that number" a statement the data can
-- support instead of a dispute. NULL re-quote columns simply mean nothing was re-quoted.
--
-- TRX_TASK.FEE_AMT IS NOT REPLACED. It stays the IDR total of these rows, so every
-- existing consumer - the detail screen, the limit ladder, the BASE_FT write - keeps
-- working untouched; this table is the breakdown behind that total, not a migration of it.
-- Whoever writes these rows is responsible for the two agreeing.
CREATE TABLE TRX_TASK_CHARGE (
    ID                NVARCHAR2(40)  NOT NULL,
    TRX_TASK_ID       NVARCHAR2(40)  NOT NULL,
    -- Component order within the task, 1-based; also what findCharges orders by, so the
    -- breakdown is presented in the same order every time it is read.
    SEQ_NO            NUMBER(2)      NOT NULL,
    -- COM_MT_CH_TYP.CD - the legacy charge type ('014' Transfer Fee, '009' LLG Fee, ...).
    CH_TYP_CD         NVARCHAR2(40)  NOT NULL,
    -- The display name frozen at submit: COM_MT_CH_TYP.NM is administrator-editable and a
    -- rename must not silently rewrite the wording on a transaction that already happened.
    CH_TYP_NM         NVARCHAR2(200),
    -- The TARIFF's own currency, which is not necessarily the transaction's.
    CCY_CD            NVARCHAR2(10)  NOT NULL,
    -- The tariff amount, in CCY_CD.
    AMT               NUMBER(25,7)   NOT NULL,
    -- The same charge expressed in IDR - the baseline every total and limit works in.
    IDR_AMT           NUMBER(25,7)   NOT NULL,
    -- The rate that produced IDR_AMT; NULL when CCY_CD is IDR (no conversion happened).
    FX_RATE           NUMBER(18,7),
    -- Core banking rate type, as in V7's RATE_TYPE: always '02' Regular for charges -
    -- kurs khusus is negotiated for the principal, never for a tariff.
    FX_RATE_TYPE      NVARCHAR2(2),
    -- Which side of the quote was taken: 'SELL' / 'BUY' / 'MID'. Recorded because the
    -- side, not just the rate, is what an auditor reconstructs the figure from.
    FX_RATE_SIDE      NVARCHAR2(4),
    -- Where the tariff came from: N'COMPANY' (CORP_CH_PC_DTL, the per-company row) or
    -- N'PACKAGE' (COM_CH_PC_DTL, the service-package template used as fallback). Kept
    -- because the two tables disagree for a company often enough that "which one did we
    -- read?" is the first question asked when a customer disputes a fee.
    TARIFF_SOURCE     NVARCHAR2(20)  NOT NULL,
    -- Set ONLY when release re-quoted the rate; see the note above.
    REQUOTED_IDR_AMT  NUMBER(25,7),
    REQUOTED_FX_RATE  NUMBER(18,7),
    REQUOTED_DT       DATE,
    VERSION           NUMBER(10)     DEFAULT 0 NOT NULL,
    CREATED_BY        NVARCHAR2(100),
    CREATED_DT        DATE           DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_TRX_TASK_CHARGE PRIMARY KEY (ID),
    CONSTRAINT FK_TRX_TASK_CHARGE_TASK FOREIGN KEY (TRX_TASK_ID) REFERENCES TRX_TASK (ID),
    -- One component per sequence number per task: this is what makes updateRequote's
    -- (task, seq) address unambiguous, and what stops a retried submit from doubling the
    -- breakdown under a total that would then no longer match FEE_AMT.
    CONSTRAINT UK_TRX_TASK_CHARGE_SEQ UNIQUE (TRX_TASK_ID, SEQ_NO)
);

-- Every read of this table is "the components of one task" (findCharges, the detail
-- screen, the re-quote at release). Without this the breakdown full-scans the table, and
-- unlike TRX_TASK it grows at several rows per transaction.
CREATE INDEX IX_TRX_TASK_CHARGE_TASK ON TRX_TASK_CHARGE (TRX_TASK_ID);
