-- The limit engine's persistence: what each task reserved, and against which limit line.
--
-- TRX_TASK is THIS service's own table (V1), so widening it is regular schema work - the
-- no-Flyway rule covers DATA and the legacy DIRECT tables, not our own DDL (same reasoning
-- as V5/V6/V7/V12). The limit rows themselves live in the legacy CORP_LMT_PC_DTL /
-- CORP_USR_GRP_LMT / COM_LMT_PC_DTL tables; this service reads and updates those, and
-- nothing here creates, alters or seeds any of them.
--
-- Column style follows V1: NVARCHAR2 text, NUMBER(25,7) amounts (BASE_FT's shape). No
-- tablespace or storage clauses - they differ per environment and would fail the migration
-- wherever the named tablespace does not exist.
--
-- Do not edit this file once it has been applied anywhere. Flyway stores its checksum and
-- fails validation at boot if it changes. Corrections go in V14.
--
-- WHY THE TASK RECORDS ITS OWN RESERVATION AT ALL. A limit reservation is made at submit
-- and given back at reject or at a failed execution, on a row in a legacy table shared with
-- everything else the company does. If the task does not record what it consumed, the
-- release has to work it out again from the task's amount, currency and account - and the
-- release runs days later, when any of those inputs may have moved. Recording the four
-- figures below makes a release an exact subtraction of what was added, and makes the daily
-- rebuild (LimitMapper.sumOpenTaskUsage) a straight GROUP BY over the tasks instead of a
-- re-derivation of every one of them.
--
-- WHY THE CURRENCY COMBINATION IS FROZEN AND NOT LOOKED UP. Which limit line applies is
-- decided by the currency COMBINATION (COM_ST_SRVC_CCY_MTRX.CCY_MTRX_CD: LL local-local, LF
-- local-forex, FL forex-local, FS forex-forex same, FC forex-forex cross), and that
-- combination is derived from the SOURCE ACCOUNT'S currency against the transaction's. The
-- source account is master data an administrator can edit while a task sits waiting for
-- approval; a task submitted as LL can therefore be sitting under an account that reads FL
-- by the time it is released. Re-deriving at release would then subtract from a line the
-- submit never added to - the original line keeps the reservation forever while the other
-- goes negative. Freezing the combination at submit is what makes that impossible.
--
-- ALL FOUR COLUMNS ARE NULL ON EXISTING ROWS AND STAY THAT WAY. Tasks submitted before this
-- migration reserved nothing under this scheme, and no backfill is done or wanted: there is
-- no way to reconstruct which line they were validated against, and a guess would be
-- indistinguishable from a fact once it is in the column. Every consumer therefore treats
-- NULL as "not attributed to a limit line" and skips the row - sumOpenTaskUsage does this
-- explicitly with LMT_SRVC_CCY_MTRX_ID IS NOT NULL.

ALTER TABLE TRX_TASK ADD (
    -- COM_ST_SRVC_CCY_MTRX.ID - the exact limit line this task was validated against, and
    -- the line its reservation sits on. Carried rather than re-resolved because the
    -- (company, service, currency) key is not unique in the legacy limit tables and a
    -- second resolution can land on a different duplicate row.
    LMT_SRVC_CCY_MTRX_ID NVARCHAR2(40),
    -- The currency-combination code (LL / LF / FL / FS / FC) that selected that line,
    -- frozen at submit - see the note above on why it must not be re-derived. Kept
    -- alongside the id because it is what a human reads when asking why this task was
    -- checked against this ceiling; the id alone answers nothing without a join.
    LMT_CCY_MTRX_CD      NVARCHAR2(4),
    -- The DENOMINATION the reservation is expressed in: the CCY_CD of the limit row that
    -- was updated, which is not necessarily the transaction's own currency. A limit ceiling
    -- is stated in one currency and every amount is converted into it before being compared
    -- or added, so this is the unit LMT_RESERVED_AMT is in and the unit any release must
    -- subtract in.
    LMT_CCY_CD           NVARCHAR2(10),
    -- The amount added to AMT_LMT_USAGE at submit, in LMT_CCY_CD - already converted, so
    -- neither the release nor the daily rebuild converts it a second time. NUMBER(25,7)
    -- matches the legacy AMT_LMT_USAGE / MAX_AMT_LMT columns exactly, so a value can move
    -- between the two without rounding. There is no matching count column: the occurrence
    -- reservation of a task is always exactly one, so storing it would only create a second
    -- place for it to be wrong.
    LMT_RESERVED_AMT     NUMBER(25,7)
);
