-- The corporate transaction workflow's own tables.
--
-- Decision recorded here so nobody "fixes" it later: legacy GCM_PENDING_TASK is NOT used.
-- The legacy application keeps its own inbox; this service's workflow is separate, so a
-- task submitted here never appears in the legacy task list and vice versa. What IS shared
-- with legacy is TRX_REF_NO_SEQUENCE (the reference-number counter) - that table already
-- exists and is deliberately absent from this migration.
--
-- Column style follows the legacy DIRECT schema these tables sit next to: NVARCHAR2 text,
-- 32-hex string surrogate keys, NUMBER(25,7) amounts (BASE_FT's shape), VERSION starting
-- at 0, CREATED_BY/CREATED_DT + UPDATED_BY/UPDATED_DT audit columns.
--
-- Approve/release land in a later phase; TRX_TASK_STAGE and TRX_TASK_ACTION already carry
-- what those phases need (stage bookkeeping, RELEASE stage rows, APPROVE/REJECT/RELEASE
-- action values) so the tables do not have to change shape under live data.
--
-- Do not edit this file once it has been applied anywhere. Flyway stores its checksum and
-- fails validation at boot if it changes. Corrections go in V2.
--
-- No tablespace or storage clauses: they differ per environment and would make the
-- migration fail wherever the named tablespace does not exist.

CREATE TABLE TRX_TASK (
    ID                NVARCHAR2(40)   NOT NULL,
    CORP_ID           NVARCHAR2(40)   NOT NULL,
    MENU_CD           NVARCHAR2(40)   NOT NULL,
    SRVC_CD           NVARCHAR2(40)   NOT NULL,
    REF_NO            NVARCHAR2(40)   NOT NULL,
    -- PENDING_APPROVAL / PENDING_RELEASE / REJECTED / READY_TO_EXECUTE / EXECUTED / FAILED
    STATUS            NVARCHAR2(30)   NOT NULL,
    CURRENT_STAGE_SEQ NUMBER(5),
    -- Denormalized instruction payload: what the maker submitted, frozen at submit time so
    -- the approval screens never depend on a joined row that an administrator can edit
    -- while the task is in flight.
    REM_ACCT_NO       NVARCHAR2(40)   NOT NULL,
    BEN_ACCT_NO       NVARCHAR2(40)   NOT NULL,
    BEN_ACCT_NM       NVARCHAR2(200),
    TRX_AMT           NUMBER(25,7)    NOT NULL,
    TRX_CCY_CD        NVARCHAR2(10)   NOT NULL,
    REMARK1           NVARCHAR2(200),
    REMARK2           NVARCHAR2(200),
    REMARK3           NVARCHAR2(200),
    INSTRUCTION_MODE  NVARCHAR2(20),
    INSTRUCTION_DT    DATE,
    -- CORP_USR.ID, not USER_ID: the login id is only unique per company and can be renamed.
    MAKER_USER_ID     NVARCHAR2(40)   NOT NULL,
    MAKER_USER_NAME   NVARCHAR2(200),
    IS_SINGLE_USER    CHAR(1)         DEFAULT 'N' NOT NULL,
    VERSION           NUMBER(10)      DEFAULT 0 NOT NULL,
    CREATED_BY        NVARCHAR2(100),
    CREATED_DT        DATE            DEFAULT SYSDATE NOT NULL,
    UPDATED_BY        NVARCHAR2(100),
    UPDATED_DT        DATE,
    CONSTRAINT PK_TRX_TASK PRIMARY KEY (ID),
    CONSTRAINT UK_TRX_TASK_REF_NO UNIQUE (REF_NO)
);

-- The task inbox of the approve/release phase filters by company and status; without this
-- it full-scans TRX_TASK the week the table gets real volume.
CREATE INDEX IX_TRX_TASK_CORP_STATUS ON TRX_TASK (CORP_ID, STATUS);

CREATE TABLE TRX_TASK_STAGE (
    ID              NVARCHAR2(40)  NOT NULL,
    TRX_TASK_ID     NVARCHAR2(40)  NOT NULL,
    SEQ_NO          NUMBER(5)      NOT NULL,
    -- APPROVAL / RELEASE
    STAGE_TYPE      NVARCHAR2(20)  NOT NULL,
    -- The approval level required of an actor in this stage; NULL means ANY level.
    APRV_LVL_CD     NVARCHAR2(40),
    -- Same digits as CORP_APRV_MTRX_DTL.USR_GRP_OPT: '1' ANY group, '2' SAME group as the
    -- maker, '3' DIFFERENT group, '4' the SPECIFIC group in CORP_USR_GRP_ID. Stored at
    -- submit; ENFORCED at the approve phase, not here.
    USR_GRP_OPT     NVARCHAR2(4),
    CORP_USR_GRP_ID NVARCHAR2(40),
    REQUIRED_COUNT  NUMBER(5)      NOT NULL,
    COMPLETED_COUNT NUMBER(5)      DEFAULT 0 NOT NULL,
    -- WAITING / ACTIVE / DONE
    STATUS          NVARCHAR2(20)  NOT NULL,
    VERSION         NUMBER(10)     DEFAULT 0 NOT NULL,
    CREATED_BY      NVARCHAR2(100),
    CREATED_DT      DATE           DEFAULT SYSDATE NOT NULL,
    UPDATED_BY      NVARCHAR2(100),
    UPDATED_DT      DATE,
    CONSTRAINT PK_TRX_TASK_STAGE PRIMARY KEY (ID),
    CONSTRAINT FK_TRX_TASK_STAGE_TASK FOREIGN KEY (TRX_TASK_ID) REFERENCES TRX_TASK (ID),
    CONSTRAINT UK_TRX_TASK_STAGE_SEQ UNIQUE (TRX_TASK_ID, SEQ_NO)
);

CREATE TABLE TRX_TASK_ACTION (
    ID                  NVARCHAR2(40)  NOT NULL,
    TRX_TASK_ID         NVARCHAR2(40)  NOT NULL,
    -- NULL on SUBMIT: the submit is not an act inside a stage.
    STAGE_SEQ           NUMBER(5),
    -- SUBMIT / APPROVE / REJECT / RELEASE
    ACTION              NVARCHAR2(20)  NOT NULL,
    ACTOR_USER_ID       NVARCHAR2(40)  NOT NULL,
    ACTOR_USER_NAME     NVARCHAR2(200),
    ACTOR_GROUP_ID      NVARCHAR2(40),
    OTP_VERIFICATION_ID NVARCHAR2(100),
    NOTE                NVARCHAR2(400),
    CREATED_DT          DATE           DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_TRX_TASK_ACTION PRIMARY KEY (ID),
    CONSTRAINT FK_TRX_TASK_ACTION_TASK FOREIGN KEY (TRX_TASK_ID) REFERENCES TRX_TASK (ID)
);

CREATE INDEX IX_TRX_TASK_ACTION_TASK ON TRX_TASK_ACTION (TRX_TASK_ID);
